// Generated by TMB: do not edit by hand

#define TMB_LIB_INIT R_init_meta_model
#include <TMB.hpp>
#include "fam_chol_matern_gmrf_gps.hpp"
#include "fam_chol_matern_gmrf_gps_us.hpp"
#include "fam_chol_matern_gmrf_gp_us.hpp"
#include "fam_chol_matern_gmrf_gs_us.hpp"
#include "fam_chol_matern_gmrf_ps_us.hpp"
#include "fam_chol_matern_gmrf_g_us.hpp"
#include "fam_chol_matern_gmrf_p_us.hpp"
#include "fam_chol_car_gmrf_sgfps_us.hpp"
#include "fam_chol_car_gmrf_sgps_us.hpp"
#include "fam_chol_car_gmrf_sgp_us.hpp"
#include "fam_chol_car_gmrf_sgs_us.hpp"
#include "fam_chol_car_gmrf_sps_us.hpp"
#include "fam_chol_car_gmrf_sg_us.hpp"
#include "fam_chol_car_gmrf_s_us.hpp"
#include "fam_chol_sar_gmrf_sgps_us.hpp"
#include "fam_chol_sar_gmrf_sgp_us.hpp"
#include "fam_chol_sar_gmrf_sgs_us.hpp"
#include "fam_chol_sar_gmrf_sps_us.hpp"
#include "fam_chol_sar_gmrf_sg_us.hpp"
#include "fam_chol_sar_gmrf_s_us.hpp"
#include "fam_chol_iid_gmrf_sgps_us.hpp"
#include "fam_chol_iid_gmrf_sgp_us.hpp"
#include "fam_chol_iid_gmrf_sgs_us.hpp"
#include "fam_chol_iid_gmrf_sps_us.hpp"
#include "fam_chol_iid_gmrf_sg_us.hpp"
#include "fam_chol_iid_gmrf_s_us.hpp"
//#include "car_gmrf.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model ==        "fam_chol_matern_gmrf_gps") {
    return fam_chol_matern_gmrf_gps(this);
  } else if(model == "fam_chol_car_gmrf_sgfps_us") {
            return fam_chol_car_gmrf_sgfps_us(this);
  } else if(model == "fam_chol_matern_gmrf_gps_us") {
            return fam_chol_matern_gmrf_gps_us(this);
  } else if(model == "fam_chol_matern_gmrf_gp_us") {
            return fam_chol_matern_gmrf_gp_us(this);
  } else if(model == "fam_chol_matern_gmrf_gs_us") {
            return fam_chol_matern_gmrf_gs_us(this);
  } else if(model == "fam_chol_matern_gmrf_ps_us") {
            return fam_chol_matern_gmrf_ps_us(this);
  } else if(model == "fam_chol_matern_gmrf_g_us") {
            return fam_chol_matern_gmrf_g_us(this);
  } else if(model == "fam_chol_matern_gmrf_p_us") {
            return fam_chol_matern_gmrf_p_us(this);
  } else if(model == "fam_chol_car_gmrf_sgps_us") {
            return fam_chol_car_gmrf_sgps_us(this);
  } else if(model == "fam_chol_car_gmrf_sgp_us") {
            return fam_chol_car_gmrf_sgp_us(this);
  } else if(model == "fam_chol_car_gmrf_sgs_us") {
            return fam_chol_car_gmrf_sgs_us(this);
  } else if(model == "fam_chol_car_gmrf_sps_us") {
            return fam_chol_car_gmrf_sps_us(this);
  } else if(model == "fam_chol_car_gmrf_sg_us") {
            return fam_chol_car_gmrf_sg_us(this);
  } else if(model == "fam_chol_car_gmrf_s_us") {
            return fam_chol_car_gmrf_s_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgps_us") {
            return fam_chol_sar_gmrf_sgps_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgp_us") {
            return fam_chol_sar_gmrf_sgp_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgs_us") {
            return fam_chol_sar_gmrf_sgs_us(this);
  } else if(model == "fam_chol_sar_gmrf_sps_us") {
            return fam_chol_sar_gmrf_sps_us(this);
  } else if(model == "fam_chol_sar_gmrf_sg_us") {
            return fam_chol_sar_gmrf_sg_us(this);
  } else if(model == "fam_chol_sar_gmrf_s_us") {
            return fam_chol_sar_gmrf_s_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgps_us") {
            return fam_chol_iid_gmrf_sgps_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgp_us") {
            return fam_chol_iid_gmrf_sgp_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgs_us") {
            return fam_chol_iid_gmrf_sgs_us(this);
  } else if(model == "fam_chol_iid_gmrf_sps_us") {
            return fam_chol_iid_gmrf_sps_us(this);
  } else if(model == "fam_chol_iid_gmrf_sg_us") {
            return fam_chol_iid_gmrf_sg_us(this);
  } else if(model == "fam_chol_iid_gmrf_s_us") {
            return fam_chol_iid_gmrf_s_us(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
