// Generated by TMB: do not edit by hand

#define TMB_LIB_INIT R_init_meta_model
#include <TMB.hpp>
#include "fam_chol_matern_gmrf_sgps.hpp"
#include "fam_chol_matern_gmrf_sgps_logit.hpp"
#include "fam_chol_matern_gmrf_sgps_overlogit.hpp"
#include "fam_chol_matern_gmrf_sgps_overpois.hpp"
#include "fam_chol_matern_gmrf_s.hpp"
#include "fam_chol_matern_gmrf_gfps.hpp"
#include "fam_chol_matern_gmrf_gps.hpp"
#include "fam_chol_matern_gmrf_sgfps.hpp"
#include "fam_chol_matern_gmrf_sgfps_us.hpp"
#include "fam_chol_matern_gmrf_sgfp_us.hpp"
#include "fam_chol_matern_gmrf_sgfs_us.hpp"
#include "fam_chol_matern_gmrf_sgps_us.hpp"
#include "fam_chol_matern_gmrf_sfps_us.hpp"
#include "fam_chol_matern_gmrf_gfps_us.hpp"
#include "fam_chol_matern_gmrf_sgf_us.hpp"
#include "fam_chol_matern_gmrf_sgp_us.hpp"
#include "fam_chol_matern_gmrf_sgs_us.hpp"
#include "fam_chol_matern_gmrf_sfp_us.hpp"
#include "fam_chol_matern_gmrf_sfs_us.hpp"
#include "fam_chol_matern_gmrf_sps_us.hpp"
#include "fam_chol_matern_gmrf_gfp_us.hpp"
#include "fam_chol_matern_gmrf_gfs_us.hpp"
#include "fam_chol_matern_gmrf_gps_us.hpp"
#include "fam_chol_matern_gmrf_fps_us.hpp"
#include "fam_chol_matern_gmrf_sg_us.hpp"
#include "fam_chol_matern_gmrf_sf_us.hpp"
#include "fam_chol_matern_gmrf_sp_us.hpp"
#include "fam_chol_matern_gmrf_ss_us.hpp"
#include "fam_chol_matern_gmrf_gf_us.hpp"
#include "fam_chol_matern_gmrf_gp_us.hpp"
#include "fam_chol_matern_gmrf_gs_us.hpp"
#include "fam_chol_matern_gmrf_fp_us.hpp"
#include "fam_chol_matern_gmrf_fs_us.hpp"
#include "fam_chol_matern_gmrf_ps_us.hpp"
#include "fam_chol_matern_gmrf_g_us.hpp"
#include "fam_chol_matern_gmrf_f_us.hpp"
#include "fam_chol_matern_gmrf_p_us.hpp"
#include "fam_chol_matern_gmrf_s_us.hpp"
#include "fam_chol_car_gmrf_sgfps_us.hpp"
#include "fam_chol_car_gmrf_sgfp_us.hpp"
#include "fam_chol_car_gmrf_sgfs_us.hpp"
#include "fam_chol_car_gmrf_sgps_us.hpp"
#include "fam_chol_car_gmrf_sgf_us.hpp"
#include "fam_chol_car_gmrf_sgp_us.hpp"
#include "fam_chol_car_gmrf_sgs_us.hpp"
#include "fam_chol_car_gmrf_sps_us.hpp"
#include "fam_chol_car_gmrf_sg_us.hpp"
#include "fam_chol_car_gmrf_s_us.hpp"
#include "fam_chol_sar_gmrf_sgfp_us.hpp"
#include "fam_chol_sar_gmrf_sgfs_us.hpp"
#include "fam_chol_sar_gmrf_sgps_us.hpp"
#include "fam_chol_sar_gmrf_sgf_us.hpp"
#include "fam_chol_sar_gmrf_sgp_us.hpp"
#include "fam_chol_sar_gmrf_sgs_us.hpp"
#include "fam_chol_sar_gmrf_sps_us.hpp"
#include "fam_chol_sar_gmrf_sg_us.hpp"
#include "fam_chol_sar_gmrf_s_us.hpp"
#include "fam_chol_iid_gmrf_sgfp_us.hpp"
#include "fam_chol_iid_gmrf_sgfs_us.hpp"
#include "fam_chol_iid_gmrf_sgps_us.hpp"
#include "fam_chol_iid_gmrf_sgf_us.hpp"
#include "fam_chol_iid_gmrf_sgp_us.hpp"
#include "fam_chol_iid_gmrf_sgs_us.hpp"
#include "fam_chol_iid_gmrf_sps_us.hpp"
#include "fam_chol_iid_gmrf_sg_us.hpp"
#include "fam_chol_iid_gmrf_s_us.hpp"
#include "rate_fam_chol_car_gmrf_g_us.hpp"
#include "rate_fam_chol_car_gmrf_gf_us.hpp"
#include "rate_fam_chol_car_gmrf_gfs_us.hpp"
#include "rate_fam_chol_car_gmrf_gp_us.hpp"
#include "rate_fam_chol_car_gmrf_gps_us.hpp"
#include "rate_fam_chol_car_gmrf_gs_us.hpp"
#include "rate_fam_chol_car_gmrf_s_us.hpp"
#include "rate_fam_chol_car_gmrf_sg_us.hpp"
#include "rate_fam_chol_car_gmrf_sgf_us.hpp"
#include "rate_fam_chol_car_gmrf_sgfs_us.hpp"
#include "rate_fam_chol_car_gmrf_sgp_us.hpp"
#include "rate_fam_chol_car_gmrf_sgps_us.hpp"
#include "rate_fam_chol_car_gmrf_sgs_us.hpp"
#include "alpha1scrtch_fam_chol_matern_gmrf_sgps_us.hpp"
#include "ratescrtch_fam_chol_car_gmrf_sgps_us.hpp"
#include "car_scrtch_fam_chol_matern_gmrf_sgps_us.hpp"
#include "fam_chol_car_gmrf_sgps_us_normalize.hpp"
//#include "car_gmrf.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model ==        "fam_chol_matern_gmrf_sgps") {
    return fam_chol_matern_gmrf_sgps(this);
  } else if(model == "fam_chol_matern_gmrf_sgps_logit") {
    return fam_chol_matern_gmrf_sgps_logit(this);
  } else if(model == "fam_chol_matern_gmrf_sgps_overlogit") {
    return fam_chol_matern_gmrf_sgps_overlogit(this);
  } else if(model == "fam_chol_matern_gmrf_sgps_overpois") {
    return fam_chol_matern_gmrf_sgps_overpois(this);
  } else if(model == "fam_chol_matern_gmrf_s") {
    return fam_chol_matern_gmrf_s(this);
  } else if(model == "fam_chol_matern_gmrf_gfps") {
    return fam_chol_matern_gmrf_gfps(this);
  } else if(model == "fam_chol_matern_gmrf_sgfps") {
    return fam_chol_matern_gmrf_sgfps(this);
  } else if(model == "fam_chol_matern_gmrf_gps") {
    return fam_chol_matern_gmrf_gps(this);
  } else if(model == "fam_chol_matern_gmrf_s") {
    return fam_chol_matern_gmrf_s(this);
  } else if(model == "fam_chol_matern_gmrf_sgfps_us") {
            return fam_chol_matern_gmrf_sgfps_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgfp_us") {
            return fam_chol_matern_gmrf_sgfp_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgfs_us") {
            return fam_chol_matern_gmrf_sgfs_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgps_us") {
            return fam_chol_matern_gmrf_sgps_us(this);
  } else if(model == "fam_chol_matern_gmrf_sfps_us") {
            return fam_chol_matern_gmrf_sfps_us(this);
  } else if(model == "fam_chol_matern_gmrf_gfps_us") {
            return fam_chol_matern_gmrf_gfps_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgf_us") {
            return fam_chol_matern_gmrf_sgf_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgp_us") {
            return fam_chol_matern_gmrf_sgp_us(this);
  } else if(model == "fam_chol_matern_gmrf_sgs_us") {
            return fam_chol_matern_gmrf_sgs_us(this);
  } else if(model == "fam_chol_matern_gmrf_sfp_us") {
            return fam_chol_matern_gmrf_sfp_us(this);
  } else if(model == "fam_chol_matern_gmrf_sfs_us") {
            return fam_chol_matern_gmrf_sfs_us(this);
  } else if(model == "fam_chol_matern_gmrf_sps_us") {
            return fam_chol_matern_gmrf_sps_us(this);
  } else if(model == "fam_chol_matern_gmrf_gfp_us") {
            return fam_chol_matern_gmrf_gfp_us(this);
  } else if(model == "fam_chol_matern_gmrf_gfs_us") {
            return fam_chol_matern_gmrf_gfs_us(this);
  } else if(model == "fam_chol_matern_gmrf_gps_us") {
            return fam_chol_matern_gmrf_gps_us(this);
  } else if(model == "fam_chol_matern_gmrf_fps_us") {
            return fam_chol_matern_gmrf_fps_us(this);
  } else if(model == "fam_chol_matern_gmrf_sg_us") {
            return fam_chol_matern_gmrf_sg_us(this);
  } else if(model == "fam_chol_matern_gmrf_sf_us") {
            return fam_chol_matern_gmrf_sf_us(this);
  } else if(model == "fam_chol_matern_gmrf_sp_us") {
            return fam_chol_matern_gmrf_sp_us(this);
  } else if(model == "fam_chol_matern_gmrf_ss_us") {
            return fam_chol_matern_gmrf_ss_us(this);
  } else if(model == "fam_chol_matern_gmrf_gf_us") {
            return fam_chol_matern_gmrf_gf_us(this);
  } else if(model == "fam_chol_matern_gmrf_gp_us") {
            return fam_chol_matern_gmrf_gp_us(this);
  } else if(model == "fam_chol_matern_gmrf_gs_us") {
            return fam_chol_matern_gmrf_gs_us(this);
  } else if(model == "fam_chol_matern_gmrf_fp_us") {
            return fam_chol_matern_gmrf_fp_us(this);
  } else if(model == "fam_chol_matern_gmrf_fs_us") {
            return fam_chol_matern_gmrf_fs_us(this);
  } else if(model == "fam_chol_matern_gmrf_ps_us") {
            return fam_chol_matern_gmrf_ps_us(this);
  } else if(model == "fam_chol_matern_gmrf_s_us") {
            return fam_chol_matern_gmrf_s_us(this);
  } else if(model == "fam_chol_matern_gmrf_g_us") {
            return fam_chol_matern_gmrf_g_us(this);
  } else if(model == "fam_chol_matern_gmrf_f_us") {
            return fam_chol_matern_gmrf_f_us(this);
  } else if(model == "fam_chol_matern_gmrf_p_us") {
            return fam_chol_matern_gmrf_p_us(this);
  } else if(model == "fam_chol_matern_gmrf_s_us") {
            return fam_chol_matern_gmrf_s_us(this);
  } else if(model == "fam_chol_car_gmrf_sgfps_us") {
            return fam_chol_car_gmrf_sgfps_us(this);
  } else if(model == "fam_chol_car_gmrf_sgfp_us") {
            return fam_chol_car_gmrf_sgfp_us(this);
  } else if(model == "fam_chol_car_gmrf_sgfs_us") {
            return fam_chol_car_gmrf_sgfs_us(this);
  } else if(model == "fam_chol_car_gmrf_sgps_us") {
            return fam_chol_car_gmrf_sgps_us(this);
  } else if(model == "fam_chol_car_gmrf_sgf_us") {
            return fam_chol_car_gmrf_sgf_us(this);
  } else if(model == "fam_chol_car_gmrf_sgp_us") {
            return fam_chol_car_gmrf_sgp_us(this);
  } else if(model == "fam_chol_car_gmrf_sgs_us") {
            return fam_chol_car_gmrf_sgs_us(this);
  } else if(model == "fam_chol_car_gmrf_sps_us") {
            return fam_chol_car_gmrf_sps_us(this);
  } else if(model == "fam_chol_car_gmrf_sg_us") {
            return fam_chol_car_gmrf_sg_us(this);
  } else if(model == "fam_chol_car_gmrf_s_us") {
            return fam_chol_car_gmrf_s_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgfp_us") {
            return fam_chol_sar_gmrf_sgfp_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgfs_us") {
            return fam_chol_sar_gmrf_sgfs_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgps_us") {
            return fam_chol_sar_gmrf_sgps_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgf_us") {
            return fam_chol_sar_gmrf_sgf_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgp_us") {
            return fam_chol_sar_gmrf_sgp_us(this);
  } else if(model == "fam_chol_sar_gmrf_sgs_us") {
            return fam_chol_sar_gmrf_sgs_us(this);
  } else if(model == "fam_chol_sar_gmrf_sps_us") {
            return fam_chol_sar_gmrf_sps_us(this);
  } else if(model == "fam_chol_sar_gmrf_sg_us") {
            return fam_chol_sar_gmrf_sg_us(this);
  } else if(model == "fam_chol_sar_gmrf_s_us") {
            return fam_chol_sar_gmrf_s_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgfp_us") {
            return fam_chol_iid_gmrf_sgfp_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgfs_us") {
            return fam_chol_iid_gmrf_sgfs_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgps_us") {
            return fam_chol_iid_gmrf_sgps_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgf_us") {
            return fam_chol_iid_gmrf_sgf_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgp_us") {
            return fam_chol_iid_gmrf_sgp_us(this);
  } else if(model == "fam_chol_iid_gmrf_sgs_us") {
            return fam_chol_iid_gmrf_sgs_us(this);
  } else if(model == "fam_chol_iid_gmrf_sps_us") {
            return fam_chol_iid_gmrf_sps_us(this);
  } else if(model == "fam_chol_iid_gmrf_sg_us") {
            return fam_chol_iid_gmrf_sg_us(this);
  } else if(model == "fam_chol_iid_gmrf_s_us") {
            return fam_chol_iid_gmrf_s_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_g_us") {
            return rate_fam_chol_car_gmrf_g_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_gf_us") {
            return rate_fam_chol_car_gmrf_gf_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_gfs_us") {
            return rate_fam_chol_car_gmrf_gfs_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_gp_us") {
            return rate_fam_chol_car_gmrf_gp_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_gps_us") {
            return rate_fam_chol_car_gmrf_gps_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_gs_us") {
            return rate_fam_chol_car_gmrf_gs_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_s_us") {
            return rate_fam_chol_car_gmrf_s_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sg_us") {
            return rate_fam_chol_car_gmrf_sg_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sgf_us") {
            return rate_fam_chol_car_gmrf_sgf_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sgfs_us") {
            return rate_fam_chol_car_gmrf_sgfs_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sgp_us") {
            return rate_fam_chol_car_gmrf_sgp_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sgps_us") {
            return rate_fam_chol_car_gmrf_sgps_us(this);
  } else if(model == "rate_fam_chol_car_gmrf_sgs_us") {
          return rate_fam_chol_car_gmrf_sgs_us(this);
  } else if(model == "alpha1scrtch_fam_chol_matern_gmrf_sgps_us") {
            return alpha1scrtch_fam_chol_matern_gmrf_sgps_us(this);
  } else if(model == "ratescrtch_fam_chol_car_gmrf_sgps_us") {
            return ratescrtch_fam_chol_car_gmrf_sgps_us(this);
  } else if(model == "car_scrtch_fam_chol_matern_gmrf_sgps_us") {
            return car_scrtch_fam_chol_matern_gmrf_sgps_us(this);
  } else if(model == "fam_chol_car_gmrf_sgps_us_normalize") {
            return fam_chol_car_gmrf_sgps_us_normalize(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
